# TEMPLATE FILE

[general]
name = "Plausible community edition" # The name of the project
repository_path = "plausible/community-edition" # The path of the repository
repository_url = "https://github.com/plausible/community-edition" # The full URL to this repository
default_port = 3001
extra_ports = [3001]

# All commands that should be run inside the VM before docker can be built.
# These commands are executed only once.
[pre_install]
commands = [
    "sed -i 's/^BASE_URL=.*/BASE_URL=${PROJECT_DOMAIN}' plausible-conf.env",
    "sed -i 's/^SECRET_KEY_BASE=.*/SECRET_KEY_BASE=${RANDOM_BYTES_32}' plausible-conf.env"
]

# Commands that should be executed everytime before starting up the docker containers.
[pre_run]
commands = []

# Commands that should be executed after starting up the docker containers.
[post_run]
commands = []

[environment]
# In case missing environment variables you can add defaults here.
# KEY = "VALUE"
# HOST = "${PROJECT_DOMAIN}"
