# TEMPLATE FILE

[general]
name = "Uptime Kuma" # The name of the project
repository_path = "louislam/uptime-kuma" # The path of the repository
repository_url = "https://github.com/louislam/uptime-kuma" # The full URL to this repository
default_port = 3001
docker_compose_path = "compose.yml"

# All commands that should be run inside the VM before docker can be built.
# These commands are executed only once.
[pre_install]
commands = []

# Commands that should be executed everytime before starting up the docker containers.
[pre_run]
commands = []

# Commands that should be executed after starting up the docker containers.
[post_run]
commands = []

[environment]
# In case missing environment variables you can add defaults here.
# KEY = "VALUE"
# HOST = "${PROJECT_DOMAIN}"
